spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-3cf0c353-diva-6648.l.aivencloud.com:12108/defaultdb?ssl-mode=REQUIRED
    username: avnadmin
    password: AVNS_9Y5_n3TBKiDGViDpuuk
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: your_company_email@gmail.com
    password: your_google_app_password
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: ${PORT:8080}

logging:
  level:
    root: INFO
